namespace Wms.Domain;

public sealed class LicensePlateNumber
{
    private LicensePlateNumber() { }
    internal LicensePlateNumber(Guid batchId) { Id = Guid.NewGuid(); BatchId = batchId; }
    public Guid Id { get; private set; }
    public Guid BatchId { get; private set; }
    // Generated by SQL Server from the global, non-cycling sequence on insert.
    public string Code { get; private set; } = null!;
    public LicensePlateNumberBatch Batch { get; private set; } = null!;
}
