// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Data;

#nullable disable

namespace Wms.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814094756_AddReceivingPutaway")]
    partial class AddReceivingPutaway
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Wms.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.DeliveryDirection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DeliveryDirections");
                });

            modelBuilder.Entity("Wms.Domain.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StockKeepingUnitId");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("WarehouseId", "StorageLocationId", "StockKeepingUnitId")
                        .IsUnique();

                    b.ToTable("InventoryBalances");
                });

            modelBuilder.Entity("Wms.Domain.InventoryCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PostedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.HasIndex("WarehouseId", "Date");

                    b.ToTable("InventoryCounts");
                });

            modelBuilder.Entity("Wms.Domain.InventoryCountItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CountedQuantity")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<double>("ExpectedQuantity")
                        .HasColumnType("float");

                    b.Property<Guid>("InventoryCountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("StockKeepingUnitId");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("InventoryCountId", "LineNumber");

                    b.ToTable("InventoryCountItems");
                });

            modelBuilder.Entity("Wms.Domain.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DestinationStorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<Guid?>("RecorderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RecorderLineNumber")
                        .HasColumnType("int");

                    b.Property<int>("RecorderType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceStorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationStorageLocationId");

                    b.HasIndex("SourceStorageLocationId");

                    b.HasIndex("StockKeepingUnitId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("Wms.Domain.InventoryTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StartedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransitStorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.HasIndex("TransitStorageLocationId")
                        .IsUnique()
                        .HasFilter("[TransitStorageLocationId] IS NOT NULL AND [Status] IN (0, 1)");

                    b.HasIndex("WarehouseId", "Date");

                    b.ToTable("InventoryTransfers");
                });

            modelBuilder.Entity("Wms.Domain.InventoryTurnover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BalanceAfter")
                        .HasColumnType("float");

                    b.Property<double>("BalanceBefore")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InventoryMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("QuantityDelta")
                        .HasColumnType("float");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InventoryMovementId");

                    b.HasIndex("StockKeepingUnitId");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryTurnovers");
                });

            modelBuilder.Entity("Wms.Domain.ReceivingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseOrderType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BusinessOperation")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<bool>("ExternalChangeDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PutawayCompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PutawayCompletedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset?>("PutawayStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PutawayStartedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("PutawayStatus")
                        .HasColumnType("int");

                    b.Property<int>("Queue")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReceivingLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StartedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WarehouseOperation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceivingLocationId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ReceivingOrders");
                });

            modelBuilder.Entity("Wms.Domain.ReceivingOrderItem", b =>
                {
                    b.Property<Guid>("ReceivingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("FactQuantity")
                        .HasColumnType("float");

                    b.Property<double>("PlanQuantity")
                        .HasColumnType("float");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReceivingOrderId", "LineNumber");

                    b.HasIndex("StockKeepingUnitId");

                    b.ToTable("ReceivingOrderItems");
                });

            modelBuilder.Entity("Wms.Domain.ShippingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DeliveryDirectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ExternalChangeDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("PickingStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PickingStartedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("PlannedShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit");

                    b.Property<int>("Queue")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ReadyForShipmentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReadyForShipmentBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipientType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RollbackReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("RolledBackAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RolledBackBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset?>("ShippedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ShippedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid?>("ShippingLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WarehouseOperation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDirectionId");

                    b.HasIndex("ShippingLocationId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ShippingOrders");
                });

            modelBuilder.Entity("Wms.Domain.ShippingOrderBaseItem", b =>
                {
                    b.Property<Guid>("ShippingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("BaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseOrderType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("PlanQuantity")
                        .HasColumnType("float");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShippingOrderId", "LineNumber");

                    b.HasIndex("StockKeepingUnitId");

                    b.ToTable("ShippingOrderBaseItems");
                });

            modelBuilder.Entity("Wms.Domain.ShippingOrderItem", b =>
                {
                    b.Property<Guid>("ShippingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("FactQuantity")
                        .HasColumnType("float");

                    b.Property<double>("PlanQuantity")
                        .HasColumnType("float");

                    b.Property<Guid>("StockKeepingUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShippingOrderId", "LineNumber");

                    b.HasIndex("StockKeepingUnitId");

                    b.ToTable("ShippingOrderItems");
                });

            modelBuilder.Entity("Wms.Domain.SkuBarcode", b =>
                {
                    b.Property<Guid>("SkuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("SkuId", "Value");

                    b.ToTable("SkuBarcodes");
                });

            modelBuilder.Entity("Wms.Domain.StockKeepingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseUnitOfMeasureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitOfMeasureId");

                    b.ToTable("StockKeepingUnits");
                });

            modelBuilder.Entity("Wms.Domain.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ZoneId");

                    b.ToTable("StorageLocations");
                });

            modelBuilder.Entity("Wms.Domain.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<double>("Denominator")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Numerator")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasure");
                });

            modelBuilder.Entity("Wms.Domain.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Wms.Domain.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DeletionMark")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Wms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Wms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("Wms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Wms.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.InventoryBalance", b =>
                {
                    b.HasOne("Wms.Domain.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Domain.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockKeepingUnit");

                    b.Navigation("StorageLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.InventoryCount", b =>
                {
                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.InventoryCountItem", b =>
                {
                    b.HasOne("Wms.Domain.InventoryCount", "InventoryCount")
                        .WithMany("Items")
                        .HasForeignKey("InventoryCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wms.Domain.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wms.Domain.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InventoryCount");

                    b.Navigation("StockKeepingUnit");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("Wms.Domain.InventoryMovement", b =>
                {
                    b.HasOne("Wms.Domain.StorageLocation", "DestinationStorageLocation")
                        .WithMany()
                        .HasForeignKey("DestinationStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wms.Domain.StorageLocation", "SourceStorageLocation")
                        .WithMany()
                        .HasForeignKey("SourceStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wms.Domain.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationStorageLocation");

                    b.Navigation("SourceStorageLocation");

                    b.Navigation("StockKeepingUnit");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.InventoryTransfer", b =>
                {
                    b.HasOne("Wms.Domain.StorageLocation", "TransitStorageLocation")
                        .WithMany()
                        .HasForeignKey("TransitStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransitStorageLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.InventoryTurnover", b =>
                {
                    b.HasOne("Wms.Domain.InventoryMovement", "InventoryMovement")
                        .WithMany()
                        .HasForeignKey("InventoryMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Domain.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Domain.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryMovement");

                    b.Navigation("StockKeepingUnit");

                    b.Navigation("StorageLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.ReceivingOrder", b =>
                {
                    b.HasOne("Wms.Domain.StorageLocation", "ReceivingLocation")
                        .WithMany()
                        .HasForeignKey("ReceivingLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceivingLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.ReceivingOrderItem", b =>
                {
                    b.HasOne("Wms.Domain.ReceivingOrder", "ReceivingOrder")
                        .WithMany("Items")
                        .HasForeignKey("ReceivingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wms.Domain.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceivingOrder");

                    b.Navigation("StockKeepingUnit");
                });

            modelBuilder.Entity("Wms.Domain.ShippingOrder", b =>
                {
                    b.HasOne("Wms.Domain.DeliveryDirection", "DeliveryDirection")
                        .WithMany()
                        .HasForeignKey("DeliveryDirectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wms.Domain.StorageLocation", "ShippingLocation")
                        .WithMany()
                        .HasForeignKey("ShippingLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryDirection");

                    b.Navigation("ShippingLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.ShippingOrderBaseItem", b =>
                {
                    b.HasOne("Wms.Domain.ShippingOrder", "ShippingOrder")
                        .WithMany("BaseItems")
                        .HasForeignKey("ShippingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wms.Domain.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShippingOrder");

                    b.Navigation("StockKeepingUnit");
                });

            modelBuilder.Entity("Wms.Domain.ShippingOrderItem", b =>
                {
                    b.HasOne("Wms.Domain.ShippingOrder", "ShippingOrder")
                        .WithMany("Items")
                        .HasForeignKey("ShippingOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wms.Domain.StockKeepingUnit", "StockKeepingUnit")
                        .WithMany()
                        .HasForeignKey("StockKeepingUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShippingOrder");

                    b.Navigation("StockKeepingUnit");
                });

            modelBuilder.Entity("Wms.Domain.SkuBarcode", b =>
                {
                    b.HasOne("Wms.Domain.StockKeepingUnit", "Sku")
                        .WithMany("Barcodes")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("Wms.Domain.StockKeepingUnit", b =>
                {
                    b.HasOne("Wms.Domain.UnitOfMeasure", "BaseUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("BaseUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnitOfMeasure");
                });

            modelBuilder.Entity("Wms.Domain.StorageLocation", b =>
                {
                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany("StorageLocations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Domain.Zone", "Zone")
                        .WithMany("StorageLocations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Wms.Domain.Zone", b =>
                {
                    b.HasOne("Wms.Domain.Warehouse", "Warehouse")
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.InventoryCount", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Wms.Domain.ReceivingOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Wms.Domain.ShippingOrder", b =>
                {
                    b.Navigation("BaseItems");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Wms.Domain.StockKeepingUnit", b =>
                {
                    b.Navigation("Barcodes");
                });

            modelBuilder.Entity("Wms.Domain.Warehouse", b =>
                {
                    b.Navigation("StorageLocations");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Wms.Domain.Zone", b =>
                {
                    b.Navigation("StorageLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
