<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wms\Wms.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\scripts\clear-wms-operational-data.sql" Link="scripts\clear-wms-operational-data.sql" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\scripts\clear-database-except-identity.sql" Link="scripts\clear-database-except-identity.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
